#!/bin/sh
# create script to start AGLauncher

DEST=""
if [ -d "$2/AccessGrid3.app" ]
then
  DEST="$2/AccessGrid3.app"
else if [ -d "$2/AccessGridToolkit3.app" ]
    then
        DEST="$2/AccessGridToolkit3.app"
    fi
fi

if [ "$DEST" == "" ]
then
  echo Failed to locate installation directory
  exit -1
fi

echo Processing installation in $DEST

echo "#!/bin/sh" > ${DEST}/Contents/MacOS/runag.sh
echo "export AGTK_APP_ROOT=${DEST}" >> ${DEST}/Contents/MacOS/runag.sh
cat ${DEST}/Contents/Resources/runag.sh.template >> ${DEST}/Contents/MacOS/runag.sh
chmod a+x ${DEST}/Contents/MacOS/runag.sh

# create script to start AGServiceManager
echo "#!/bin/sh" > ${DEST}/Contents/MacOS/runsm.sh
echo "export AGTK_APP_ROOT=${DEST}" >> ${DEST}/Contents/MacOS/runsm.sh
cat ${DEST}/Contents/Resources/setupenv.sh.template >> ${DEST}/Contents/MacOS/runsm.sh
echo 'pythonw "$AGTK_LOCATION/bin/AGServiceManager3.py"' >> ${DEST}/Contents/MacOS/runsm.sh
chmod a+x ${DEST}/Contents/MacOS/runsm.sh

# create script to start VenueServer
echo "#!/bin/sh" > ${DEST}/Contents/MacOS/runvs.sh
echo "export AGTK_APP_ROOT=${DEST}" >> ${DEST}/Contents/MacOS/runvs.sh
cat ${DEST}/Contents/Resources/setupenv.sh.template >> ${DEST}/Contents/MacOS/runvs.sh
echo 'pythonw "$AGTK_LOCATION/bin/VenueServer3.py"' >> ${DEST}/Contents/MacOS/runvs.sh
chmod a+x ${DEST}/Contents/MacOS/runvs.sh

# create script to start AGNodeService
echo "#!/bin/sh" > ${DEST}/Contents/MacOS/runns.sh
echo "export AGTK_APP_ROOT=${DEST}" >> ${DEST}/Contents/MacOS/runns.sh
cat ${DEST}/Contents/Resources/setupenv.sh.template >> ${DEST}/Contents/MacOS/runns.sh
echo 'pythonw "$AGTK_LOCATION/bin/AGServiceManager3.py" -n' >> ${DEST}/Contents/MacOS/runns.sh
chmod a+x ${DEST}/Contents/MacOS/runns.sh


# create sh environment setup script
echo "#!/bin/sh" > ${DEST}/Contents/Resources/setupenv.sh
echo "export AGTK_APP_ROOT=${DEST}" >> ${DEST}/Contents/Resources/setupenv.sh
cat ${DEST}/Contents/Resources/setupenv.sh.template >> ${DEST}/Contents/Resources/setupenv.sh

# create csh environment setup script
echo "#!/bin/csh" > ${DEST}/Contents/Resources/setupenv.csh
echo "setenv AGTK_APP_ROOT ${DEST}" >> ${DEST}/Contents/Resources/setupenv.csh
cat ${DEST}/Contents/Resources/setupenv.csh.template >> ${DEST}/Contents/Resources/setupenv.csh

# setup shared applications
. ${DEST}/Contents/Resources/setupenv.sh
# Use pythonw so installed applications can start a user interface
export AGTK_USER=/var/log/accessgrid
/usr/bin/pythonw ${DEST}/Contents/Resources/bin/agpm3.py --post-install

# remove temporary files used during installation above
/bin/rm ${DEST}/Contents/Resources/runag.sh.template
/bin/rm ${DEST}/Contents/Resources/setupenv.sh.template
/bin/rm ${DEST}/Contents/Resources/setupenv.csh.template
