#!/bin/sh

set -e 

####/usr/sbin/update-python-modules -f

case "$1" in
	purge)
		[ -d /usr/share/AccessGrid3 ] && {
			echo "Deleting any unremoved files/directories from /usr/share/AccessGrid3" >&2
			rm -rf /usr/share/AccessGrid3
		}
		[ -d /etc/AccessGrid3 ] && {
			echo "Deleting any unremoved files/directories from /etc/AccessGrid3" >&2
			rm -rf /etc/AccessGrid3
		}
	;;
	*)
		echo "POSTRM called with argument: $1" >&2
	;;
esac

exit 0

