#!/bin/sh


if [ ! "${EUID}" = "0" ]; then
  echo "Must be root to run this script"
  exit 1
fi

# In case someone is using sudo
#
PATH=/sbin:${PATH}

arch=${ARCH:-`uname -m`}
SL_VERSION="SL12"

# Package names
#
pkgs="
AccessGrid-3.2-noarch-0r6575.tgz
quickbridge-3.0.2-${arch}-1.tgz
elementtree-1.2.6-20050316-${arch}-1.tgz
bajjer-0.2.5-${arch}-3.tgz
feedparser-4.1-${arch}-1.tgz
pyxml-0.8.4-${arch}-1.tgz
m2crypto-0.17-${arch}-2.tgz
zopeinterface-3.3.0-${arch}-1.tgz
twistedcore-2.5.0-${arch}-1.tgz
ag-zsi-r1385-${arch}-2.tgz
common-0.1-${arch}-3.tgz
ag-rat-4.4.00-r4080-${arch}-3.tgz
ag-vic-2.8ucl-1.3.1-${arch}-0r4126.tgz
"
noAvahi="
mDNSResponder-107.6-${arch}-1.tgz
bonjour-py-0.1-${arch}-1.tgz
"
prereqs="
wxPython-2.8-gtk2-unicode-py2.5-2.8.4.0-${arch}-4.tgz
xulrunner-1.8.0.4-${arch}-1.tgz
wxmozilla-20070620cvs-${arch}-3.tgz
"
noinstall="
hdvideoservices-0.1-noarch-1.tgz
"


version=3.2
release=0r6575-1
releasedir=${RELEASEDIR:-/scratch/AG3/releases-12.0}
pkgdir=${PKGDIR:-/tmp}

tempdirname=${pkgdir}/ag_install_`date +%Y%m%d`
bundledirname=AG-install-${version}-${SL_VERSION}.${arch}-${release}
bundledir=${tempdirname}/${bundledirname}

if [ ! -d ${releasedir} ]; then
  echo "Please set RELEASEDIR to directory containing AG packages"
  exit 1
fi
mkdir -p ${bundledir} ||exit 1
for p in ${pkgs}; do
  cp ${releasedir}/${p} ${bundledir}/
done
for p in ${noAvahi}; do
  cp ${releasedir}/${p} ${bundledir}/
done
for p in ${prereqs}; do
  cp ${releasedir}/${p} ${bundledir}/
done

cat <<EOF >install-${SL_VERSION}-${arch}.sh
#!/bin/sh

if [ ! "\${EUID}" = "0" ]; then
  echo "Must be root to run this script"
  exit 1
fi

# In case someone is using sudo
#
PATH=/sbin:\${PATH}

arch=\`uname -m\`

pkg () 
{ 
    /bin/ls \$LS_OPTIONS /var/adm/packages | grep \$*
}
proc () 
{ 
    ps -ef | grep \$* | grep -v grep
}

cruft_to_remove="
AccessGrid-3.1-noarch-cvs20070808
AccessGrid-3.1-noarch-cvs20071010
AccessGrid-3.1-noarch-cvs20071010-1
AccessGrid-3.1-noarch-cvs20071031-1
AccessGrid-3.1-noarch-cvs20071215-1
"

pkgs="
EOF
for p in $pkgs; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"

do_uninstall () {
  echo "Doing uninstall"
  for p in \${pkgs} ; do
    unp=\`basename \${p} .tgz\`
    removepkg \${unp}
  done
}

UNINSTALL=0
while [ \$# -gt 0 ]; do
  echo \$1
  if [ x"\$1" == x"--uninstall" ]; then
    UNINSTALL=1
  fi
  shift
done
if [ \$UNINSTALL -gt 0 ]; then
  echo "do_uninstall"
  do_uninstall
  exit 1
fi

echo -n "Removing cruft ... "
for cruft in \${cruft_to_remove} ; do
  echo -n " ."
  removepkg \${cruft} >/dev/null 2>/dev/null
done
echo
EOF

cat <<EOF >>install-${SL_VERSION}-${arch}.sh
noAvahi="
EOF
for p in ${noAvahi}; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"
EOF


cat <<EOF >>install-${SL_VERSION}-${arch}.sh

prereqs="
EOF
for p in ${prereqs}; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"

for p in \${prereqs}; do
  pkg \${p}
  if [ \$? -ne 0 ]; then
    upgradepkg --reinstall --install-new \${p}
  fi 
done

for p in \${pkgs}; do
  upgradepkg --reinstall --install-new \${p}
done


# May have to install mDNS too
#
proc avahi
if [ \$? -ne 0 ]; then
  for p in \${noAvahi}; do
    upgradepkg --reinstall --install-new \${p}
  done
fi

EOF


cp install-${SL_VERSION}-${arch}.sh ${bundledir}/
chmod 0755 ${bundledir}/install-${SL_VERSION}-${arch}.sh

# Make a self extracting installer
#
if [ -x /usr/bin/makeself.sh ]; then
  echo "Creating self installer ..."
  makeself.sh ${bundledir} ${releasedir}/${bundledirname}.run "AG3.2 installer for Slackware ${SL_VERSION}" ./install-${SL_VERSION}-${arch}.sh
else
  echo "Can't generate self installer"
fi

cd ${tempdirname} && tar zcvf ${bundledirname}.tar.gz ${bundledirname}
rm -rf ${bundledir}

# Changelog
#
# Pre-beta 3.2 20080315
#  - pre-beta AG-3.2 (svn r6575-1)
#  - with ag-vic2.8ucl-1.3.1 (svn r4126)
#
# Release 3.1-1
#  - 3.1 release
#
# Release 20071215-1
#  - new 3.1beta2 snapshot
#  - update bajjer to 0.2.5 release 3
#
# Release 20071031-1
#  - new 3.1beta2 snapshot
#
# Release 20071010-2
#  - patched 3.1beta2 (cvs20071010-1)
#  - update wxmozilla to 20070620cvs-${arch}-3
#
# Release 20071010-1
#  - 3.1beta2 (cvs20071010)
#
# Release cvs 20071005-1
#  - update bajjer to 0.2.5 release 2
#
# Release cvs20070808-3 20070926
#  - update wxPython (release 4)
#  - added --uninstall option
#
# Release cvs20070808-2 20070810
#  - update ag-vic to r4086
#
# Release cvs20070808-1 20070808
#  - new snapshot
#  - add self-extracting installer
#
# Release 1, 20070629 for SL-12.0
#
