#!/bin/sh


if [ $# -gt 0 ]; then
  TARGET=$1
else
  TARGET=python
fi
echo "Target: ${TARGET}"

for i in `ps -ef | grep ${TARGET} | grep -v grep | awk ' $3 == 1 { print $2 }'`
do
  echo "kill -HUP $i"
  kill -KILL $i
done

#/usr/bin/setpwc -d /dev/video0 -r

