#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"\x13\x05Cu\xae\xc4`u\x05\x85d\x05e\x03 \xb00\
\x00\xf3\xf5@|70\x00\xf3\xf3A|g\x03\x10\x04\xf3#@|\x0b\x03\x0b\x98z\x054\x80\
OP\x0f\t\xe0\x17\xc4e\xa6\x1e\x14c\x15D2\x13.\x10\x81"\x08\x05\xf9\xd8\x04\
\xf5P\x05\xc1\x12\x11\xd8\x04\xf3\xb1\t\x92\xed#TA=\x009\xd4G\x07' ))

def getBitmap():
    return wxBitmapFromXPMData(getData())

def getImage():
    return wxImageFromBitmap(getBitmap())

