#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"c\x05Cu\xae\xc4`u=\x85d\x05e70\x00\xf3#@|g\
\x03\x10\x04\xf3\x15\xc0|g33\x03\x18\x1f\x15\xe0\x13\xd4C\x02\x08A\x842\x0cA\
\x90:TA=,*\xf5\xf40U\x82m@W\x89U0\x02\xe6\x1e\x143A\xa2\x11\xd8\x9c\xa4@\x84\
 6o\x12\x17Jz\x00\xd6lC\x97' ))

def getBitmap():
    return wxBitmapFromXPMData(getData())

def getImage():
    return wxImageFromBitmap(getBitmap())

