#!/bin/sh


if [ ! "${EUID}" = "0" ]; then
  echo "Must be root to run this script"
  exit 1
fi

# In case someone is using sudo
#
PATH=/sbin:${PATH}

arch=${ARCH:-`uname -m`}
SL_VERSION="SL11"

# Package names
#
pkgs="
AccessGrid-3.1-noarch-cvs20071010.tgz
quickbridge-3.0.2-${arch}-1.tgz
elementtree-1.2.6-20050316-${arch}-1.tgz
bajjer-0.2.5-${arch}-2.tgz
feedparser-4.1-${arch}-1.tgz
pyxml-0.8.4-${arch}-1.tgz
m2crypto-0.17-${arch}-2.tgz
zopeinterface-3.3.0-${arch}-1.tgz
twistedcore-2.5.0-${arch}-1.tgz
ag-zsi-r1385-${arch}-2.tgz
common-0.1-${arch}-3.tgz
ag-rat-4.4.00-r4080-${arch}-3.tgz
ag-vic-2.8ucl-1.3.0-r4086-${arch}-1.tgz
"
noAvahi="
mDNSResponder-107.6-${arch}-1.tgz
bonjour-py-0.1-${arch}-1.tgz
"
old_prereqs="
wxPython-2.6-gtk2-ansi-2.6.3.2-${arch}-4.tgz
wxmozilla-20061219cvs-${arch}-1.tgz
"
prereqs="
wxPython-2.8-gtk2-unicode-py2.4-2.8.4.0-${arch}-4.tgz
xulrunner-1.8.0.4-${arch}-1.tgz
wxmozilla-20070620cvs-${arch}-1.tgz
"

version=3.1
release=cvs20071010-1
releasedir=${RELEASEDIR:-/scratch/AG3/releases-11.0}
pkgdir=${PKGDIR:-/tmp}

tempdirname=${pkgdir}/ag_install_`date +%Y%m%d`
bundledirname=AG-install-${version}-${SL_VERSION}.${arch}-${release}
bundledir=${tempdirname}/${bundledirname}

if [ ! -d ${releasedir} ]; then
  echo "Please set RELEASEDIR to directory containing AG packages"
  exit 1
fi
mkdir -p ${bundledir} ||exit 1
for p in ${pkgs}; do
  cp ${releasedir}/${p} ${bundledir}/
done
for p in ${noAvahi}; do
  cp ${releasedir}/${p} ${bundledir}/
done
for p in ${prereqs}; do
  cp ${releasedir}/${p} ${bundledir}/
done

cat <<EOF >install-${SL_VERSION}-${arch}.sh
#!/bin/sh

if [ ! "\${EUID}" = "0" ]; then
  echo "Must be root to run this script"
  exit 1
fi

# In case someone is using sudo
#
PATH=/sbin:\${PATH}

arch=\`uname -m\`

pkg () 
{ 
    /bin/ls \$LS_OPTIONS /var/adm/packages | grep \$*
}
proc () 
{ 
    ps -ef | grep \$* | grep -v grep
}

pkgs="
EOF
for p in $pkgs; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"

do_uninstall () {
  echo "Doing uninstall"
  for p in \${pkgs} ; do
    unp=\`basename \${p} .tgz\`
    removepkg \${unp}
  done
}

UNINSTALL=0
while [ \$# -gt 0 ]; do
  echo \$1
  if [ x"\$1" == x"--uninstall" ]; then
    UNINSTALL=1
  fi
  shift
done
if [ \$UNINSTALL -gt 0 ]; then
  echo "do_uninstall"
  do_uninstall
  exit 1
fi

EOF

cat <<EOF >>install-${SL_VERSION}-${arch}.sh
noAvahi="
EOF
for p in ${noAvahi}; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"
EOF


cat <<EOF >>install-${SL_VERSION}-${arch}.sh

prereqs="
EOF
for p in ${prereqs}; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"

for p in \${prereqs}; do
  pkg \${p}
  if [ \$? -ne 0 ]; then
    upgradepkg --reinstall --install-new \${p}
  fi 
done

for p in \${pkgs}; do
  upgradepkg --reinstall --install-new \${p}
done

# May have to install mDNS too
#
proc avahi
if [ \$? -ne 0 ]; then
  for p in \${noAvahi}; do
    upgradepkg --reinstall --install-new \${p}
  done
fi

EOF


cp install-${SL_VERSION}-${arch}.sh ${bundledir}/
chmod 0755 ${bundledir}/install-${SL_VERSION}-${arch}.sh

# Make a self extracting installer
#
if [ -x /usr/bin/makeself.sh ]; then
  echo "Creating self installer ..."
  makeself.sh ${bundledir} ${releasedir}/${bundledirname}.run "AG3.1 installer for Slackware ${SL_VERSION}" ./install-${SL_VERSION}-${arch}.sh
else
  echo "Can't generate self installer"
fi

cd ${tempdirname} && tar zcvf ${bundledirname}.tar.gz ${bundledirname}
rm -rf ${bundledir}

# Changelog
#
# Release cvs 20071010-1
#  - 3.1beta2
#
# Release cvs 20071005-1
#  - update bajjer to 0.2.5 release 2
#
# Release cvs20070808-3 20070926
#  - update wxPython (release 4)
#
# Release cvs20070808-2 20070810
#  - update ag-vic to r4086
#
# Release cvs20070808-1 20070808
#  - new snapshot
#  - add self-extracting installer
#
# Release cvs20070721b 20070730
#  - AcccessGrid patched to enable use of wxPython-2.8.4.0
#  - use wxPython-2.8, xulrunner & wxmozilla-20070629
#
# Release cvs20070705 - beta1 snapshot
#
# Release cvs20070627 - 3.1 beta1 snapshot (actually 20070629)
#

