#!/bin/sh


if [ ! "${EUID}" = "0" ]; then
  echo "Must be root to run this script"
  exit 1
fi

# In case someone is using sudo
#
PATH=/sbin:${PATH}

arch=${ARCH:-`uname -m`}
grep "Slackware 11." /etc/slackware-version 2>&1 >/dev/null
if [ $? -eq 0 ]; then
  SL_VERSION="SL11"
else
  SL_VERSION="SL10"
fi

# Package names
#
pkgs="
AccessGrid-3.0.2-${arch}-7.tgz
quickbridge-3.0.2-${arch}-1.tgz
elementtree-1.2.6-20050316-${arch}-1.tgz
bajjer-0.2.5-${arch}-1.tgz
TwistedCore-2.4.0-${arch}-3.tgz
ZopeInterface-3.0.1-${arch}-2.tgz
ag-zsi-r1385-${arch}-2.tgz
common-0.1-${arch}-3.tgz
feedparser-4.1-${arch}-1.tgz
m2crypto-0.17-${arch}-2.tgz
pyOpenSSL-0.5.1-${arch}-2.tgz
pyxml-0.8.4-${arch}-1.tgz
ag-rat-4.4.00-${arch}-2.tgz
"
noAvahi="
mDNSResponder-107.6-${arch}-1.tgz
bonjour-py-0.1-${arch}-1.tgz
"
prereqs="
wxPython-2.6-gtk2-ansi-2.6.3.2-${arch}-4.tgz
"
WXMOZ_SL10=wxmozilla-0.5.6-${arch}-1.tgz
WXMOZ_SL11=wxmozilla-20061219cvs-${arch}-1.tgz
X86_64_VIC=ag-vic-2.8ucl-1.3.0-x86_64-1.tgz
IA32_VIC=ag-vic-2.8ucl-1.1.3-AG-i686-2.tgz

version=3.0.2
release=7
releasedir=${RELEASEDIR:-/scratch/AG3/releases}
pkgdir=${PKGDIR:-/tmp}

tempdirname=${pkgdir}/ag_install_`date +%Y%m%d`
bundledirname=AG-install-${version}-${SL_VERSION}.${arch}-${release}
bundledir=${tempdirname}/${bundledirname}

if [ ! -d ${releasedir} ]; then
  echo "Please set RELEASEDIR to directory containing AG packages"
  exit 1
fi
mkdir -p ${bundledir} ||exit 1
for p in ${pkgs}; do
  cp ${releasedir}/${p} ${bundledir}/
done
if [ ${arch} = "x86_64" ]; then
  cp ${releasedir}/${X86_64_VIC} ${bundledir}/
else
  cp ${releasedir}/${IA32_VIC} ${bundledir}/
fi
for p in ${noAvahi}; do
  cp ${releasedir}/${p} ${bundledir}/
done
for p in ${prereqs}; do
  cp ${releasedir}/${p} ${bundledir}/
done
cp ${releasedir}/${WXMOZ_SL10} ${bundledir}/
cp ${releasedir}/${WXMOZ_SL11} ${bundledir}/

cat <<EOF >install-${SL_VERSION}-${arch}.sh
#!/bin/sh

if [ ! "\${EUID}" = "0" ]; then
  echo "Must be root to run this script"
  exit 1
fi

# In case someone is using sudo
#
PATH=/sbin:\${PATH}

arch=\`uname -m\`

WXMOZ_SL10=${WXMOZ_SL10}
WXMOZ_SL11=${WXMOZ_SL11}

pkg () 
{ 
    /bin/ls \$LS_OPTIONS /var/adm/packages | grep \$*
}
proc () 
{ 
    ps -ef | grep \$* | grep -v grep
}

pkgs=""
if [ \$# -eq 0 ]; then
  pkgs="
EOF
for p in $pkgs; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"
else
  while [ \$# -gt 0 ]; do
    pkgs="\${pkgs} \${1}"
    shift
  done
fi

EOF

cat <<EOF >>install-${SL_VERSION}-${arch}.sh
noAvahi="
EOF
for p in ${noAvahi}; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"
EOF


cat <<EOF >>install-${SL_VERSION}-${arch}.sh

prereqs="
EOF
for p in ${prereqs}; do
  echo ${p} >>install-${SL_VERSION}-${arch}.sh
done
cat <<EOF >>install-${SL_VERSION}-${arch}.sh
"

for p in \${prereqs}; do
  pkg \${p}
  if [ \$? -ne 0 ]; then
    upgradepkg --reinstall --install-new \${p}
  fi 
done

for p in \${pkgs}; do
  upgradepkg --reinstall --install-new \${p}
done

# Use new UCL vic for X86_64
if [ \${arch} = "x86_64" ]; then
  upgradepkg --reinstall --install-new ${X86_64_VIC}
else
  upgradepkg --reinstall --install-new ${IA32_VIC}
fi

# wxmozilla depends on SL release
#
SLR=\`grep "Slackware 11." /etc/slackware-version\`
if [ \$? -eq 0 ]; then
  upgradepkg --reinstall --install-new \${WXMOZ_SL11}
else
  upgradepkg --reinstall --install-new \${WXMOZ_SL10}
fi

# May have to install mDNS too
#
proc avahi
if [ \$? -ne 0 ]; then
  for p in \${noAvahi}; do
    upgradepkg --reinstall --install-new \${p}
  done
fi

EOF


cp install-${SL_VERSION}-${arch}.sh ${bundledir}/
chmod 0755 ${bundledir}/install-${SL_VERSION}-${arch}.sh

#if [ ${arch} = "x86_64" ]; then
#  mkdir ${bundledir}/tmp
#  cd ${bundledir}/tmp
#  tar-1.13 zxvf ../AccessGrid-3.0.2-${arch}-4.tgz
#  cp ${releasedir}/AudioService.zip.32bit etc/AccessGrid3/NodeServices/AudioService.zip
#  chown -R root:root .
#  tar-1.13 zcvf ../AccessGrid-3.0.2-${arch}-4.tgz .
#  cd ${bundledir} && rm -rf tmp
#
#fi

cd ${tempdirname} && tar zcvf ${bundledirname}.tar.gz ${bundledirname}
rm -rf ${bundledir}

# Changelog
#
# Release 6, 20070507
#  - update ag-zsi (r1376)
#  - separate ag-vic & ag-rat
#
# Release 5, 20070312
#  - update wxPython2.6 to release 4 (include docs & samples)
#  - update ag-zsi to r1365 (from branches) and
#    rebuild m2crypto, TwistedCore, common, AccessGrid
#
# Release 4, 20061219
#  - Updated common TwistedCore m2crypto swig ag-zsi ZopeInterface
#    Bajjer pyOpenSSL wxPython
#  - Included RegistryClient.py from cvs in AccessGrid-3.0.2
#  - New wxmozilla for SL11
#
# Release 3, 20061011
#  - Replaced x86_64 AudioService with that of 32bit release
#    (since x_86_64 compiled rat doesn't display properly)
#
# Release 2, 20060810
#  - updated to release 2 of Twisted-2.1.0 with threadedselectreactor patch
#
