#!/bin/sh
#
# agns		This shell script takes care of starting and stopping
#		the Access Grid Node Service
#
# chkconfig: - 90 10
# description: The Access Grid Service Manager

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

[ -x /usr/bin/AGNodeService.py ] || exit 

RETVAL=0
prog="AGNodeService"
datadir="/var/run/agns"

start() {
    # Start daemons.
    touch /var/log/agns.log
    chown ag.ag /var/log/agns.log
    chmod 0640 /var/log/agns.log
    if [ ! -d $datadir ]; then
	mkdir -p $datadir
	chown -R ag.ag $datadir
	chmod 0640 $datadir
    fi
    echo -n $"Starting $prog: "
    daemon --user ag AGNodeService.py
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/agns
    return $RETVAL
}

stop() {
    # Stop daemons.
    echo -n $"Shutting down $prog: "
    killproc AGNodeService.py
    RETVAL=$?
    echo
    if [ -d $datadir ]; then
	rm -rf $datadir
    fi
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/agns
    return $RETVAL
}

# See how we were called.
case "$1" in
    start)
	start
        ;;
    stop)
	stop
        ;;
    status)
	status agns
	RETVAL=$?
	;;
    restart|reload)
	stop
	start
	RETVAL=$?
	;;
    condrestart)
	if [ -f /var/lock/subsys/agns ]; then
	    stop
	    start
	    RETVAL=$?
	fi
	;;
    *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $RETVAL
